// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ResetUsers.sql

package database

import (
	"context"
)

const resetUsers = `-- name: ResetUsers :exec
delete from users *
`

func (q *Queries) ResetUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUsers)
	return err
}
